User Authentication
anim-13/project---E-State_app pull request #1
Opened 2021-03-03 08:25 UTC by anim-13

Implemented User Authentication . i.e sign up and log in/out

2021-03-04 11:23 UTC, kalpana19sharma requested changes
@anim-13 please remove unused test files.

2021-03-04 11:23 UTC, kalpana19sharma commented on app/assets/stylesheets/sessions.scss
> +// You can use Sass (SCSS) here: https://sass-lang.com/
Remove this unnecessary file

2021-03-04 11:23 UTC, kalpana19sharma commented on app/assets/stylesheets/users.scss
> +// You can use Sass (SCSS) here: https://sass-lang.com/
Remove this unnecessary file

2021-03-04 11:23 UTC, kalpana19sharma commented on app/controllers/application_controller.rb
> +
Remove unnecessary empty lines.

2021-03-04 11:23 UTC, kalpana19sharma commented on app/controllers/application_controller.rb
> +    @current_user ||= User.find(session[:user_id]) if session[:user_id]
1. What does `||=` operator do?
2. What's the difference between `find` and `find_by`

2021-03-04 11:23 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +
Remove unnecessary empty line.

2021-03-04 11:23 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +  end
For empty methods we use single line syntax 
```suggestion
  def new; end
```

2021-03-04 11:23 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +
Remove unnecessary empty line.

2021-03-04 11:23 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +
Remove unnecessary empty line.

2021-03-04 11:23 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +end
Add an empty line at the end of the file.

2021-03-04 11:23 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +    if user && user.authenticate(params[:login][:password])
Use strong parameters

2021-03-04 11:23 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +
Remove unnecessary empty line

2021-03-04 11:23 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    @user.email.downcase!
What's this for?

2021-03-04 11:23 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +private
Fix indentation

2021-03-04 11:23 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +end
Add an empty line at the end of the file.

2021-03-04 11:23 UTC, kalpana19sharma commented on app/helpers/sessions_helper.rb
> +end
Remove unnecessary file

2021-03-04 11:23 UTC, kalpana19sharma commented on app/helpers/users_helper.rb
> +end
Remove unnecessary file.

2021-03-04 11:23 UTC, kalpana19sharma commented on app/models/user.rb
> +end
Fix indentation

2021-03-04 11:23 UTC, kalpana19sharma commented on app/views/layouts/application.html.erb
> +    <% end %>
You can extract this logic in a partial

2021-03-04 11:23 UTC, kalpana19sharma commented on app/views/sessions/new.html.erb
> +<% end %>
empty line.

2021-03-04 11:23 UTC, kalpana19sharma commented on app/models/user.rb
> +	validates :email, presence: true, uniqueness: true
No validations on password?

2021-03-04 11:23 UTC, kalpana19sharma commented on app/views/users/new.html.erb
> +<% end %>
empty line.

2021-03-04 11:23 UTC, kalpana19sharma commented on config/routes.rb
> +end
Fix indentation.

2021-03-04 11:23 UTC, kalpana19sharma commented on config/routes.rb
> +	post 'users' => 'users#create'
Can we use resources here?

2021-03-04 11:24 UTC, kalpana19sharma commented
@anim-13 add proper screenshots in the PR description

2021-03-08 05:24 UTC, kalpana19sharma requested changes

2021-03-08 05:24 UTC, kalpana19sharma commented on app/controllers/application_controller.rb
> +
I think some whitespaces are added here.

2021-03-08 05:24 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +    if user && user.authenticate(session_params['password'])
1. Use symbol syntax
```suggestion
    if user && user.authenticate(session_params[:password]) 
```
2. Use `&.` operator

2021-03-08 05:24 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    @user.email.downcase!
What's this logic for? Isn't this should be in model?

2021-03-08 05:24 UTC, kalpana19sharma commented on app/models/user.rb
> +  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
Fix indentation

2021-03-08 05:24 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +      flash.now.alert = "Enter valid email and password and try again."
If you are showing error messages on the form then I think you can skip the flash message

2021-03-08 05:24 UTC, kalpana19sharma commented on app/helpers/application_helper.rb
> -end
Don't remove the files from initial commit.

2021-03-08 05:24 UTC, kalpana19sharma commented on app/views/layouts/_navigation.html.erb
> +
Whitesapces

2021-03-08 05:24 UTC, kalpana19sharma commented on app/views/layouts/_navigation.html.erb
> +<% end %>
Can we refactor this logic?

2021-03-08 05:24 UTC, kalpana19sharma commented on app/views/layouts/application.html.erb
> +    <%= render "layouts/navigation"%>
Use proper spaces

2021-03-08 05:24 UTC, kalpana19sharma commented on app/views/layouts/_navigation.html.erb
> +<% if notice %>
Why this filename is `navigation`?

2021-03-08 05:24 UTC, kalpana19sharma commented on config/database.yml
> +  password: password
Don't commit the passwords

2021-03-08 05:24 UTC, kalpana19sharma commented on config/routes.rb
> +	delete '/logout'   => 'sessions#destroy'
Fix indentation

2021-03-08 05:24 UTC, kalpana19sharma commented on config/routes.rb
> +  resources :users
Do we need all of the default routes?

2021-03-08 05:24 UTC, kalpana19sharma commented on test/controllers/sessions_controller_test.rb
> +end
Remove unnecessary test files

2021-03-08 06:59 UTC, anim-13 commented on app/views/layouts/_navigation.html.erb
> +<% if notice %>
changed to mesage.html.erb

2021-03-08 11:23 UTC, kalpana19sharma requested changes

2021-03-08 11:23 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +    if user && user.authenticate(session_params[:password])
Use `&.` operator

2021-03-08 11:23 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +      session[:user_id] = user.id.to_s
Do we really need to use `to_s` here?

2021-03-08 11:23 UTC, kalpana19sharma commented on app/controllers/sessions_controller.rb
> +    user = User.find_by(email: session_params[:email])
Use a before filter to initialize the user.

2021-03-08 11:23 UTC, kalpana19sharma commented on app/helpers/application_helper.rb
> -end
Restore this file.

2021-03-08 11:23 UTC, kalpana19sharma commented on app/helpers/application_helper.rb
> -end
It was added in initial commit and not generated when you created a controller.

2021-03-08 11:23 UTC, kalpana19sharma commented on app/models/user.rb
> +  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
??

2021-03-08 11:23 UTC, kalpana19sharma commented on config/routes.rb
> +  resources :users
??

2021-03-08 11:23 UTC, kalpana19sharma commented on test/fixtures/users.yml
> +  password_digest: MyString
Remove this file

2021-03-08 11:23 UTC, kalpana19sharma commented on test/models/user_test.rb
> +end
Remove this file

2021-03-09 08:56 UTC, kalpana19sharma requested changes

2021-03-09 08:56 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    end
Fix indentation
```suggestion
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end  
```

2021-03-09 08:56 UTC, kalpana19sharma commented on app/helpers/application_helper.rb 
> +end
No new line at the end of the file.

2021-03-09 08:56 UTC, kalpana19sharma commented on app/models/user.rb
> +  has_secure_password
Add an empty line above `has_secure_password`

2021-03-09 08:56 UTC, kalpana19sharma commented on config/routes.rb
> +	delete '/logout' => 'sessions#destroy'
Indentation?

2021-03-09 08:56 UTC, kalpana19sharma commented on test/fixtures/users.yml
> +  password_digest: MyString
Remove this file.

2021-03-09 12:02 UTC, kalpana19sharma approved these changes

2021-03-09 12:02 UTC, merged